[package]
name = "checks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.59"
bitflags = "1.3.2"

[dev-dependencies]
tokio = { version = "1.23.0", features = ["time", "rt", "macros"] }
