[package]
name = "checks"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arbitrary = { version = "1.3.2", features = ["derive"], optional = true }
async-trait = "0.1.59"
bitflags = "2.5.0"

[dev-dependencies]
tokio = { version = "1.23.0", features = ["time", "rt", "macros"] }

[features]
arbitrary = ["dep:arbitrary", "bitflags/arbitrary"]
