[package]
name = "pyopenchecks"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/scott-wilson/openchecks/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "openchecks"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.3" }
# base_openchecks = { git = "https://github.com/scott-wilson/openchecks.git", rev = "b57d12aec35feebdf5220ae8544a2782539ce6da", package = "openchecks" }
base_openchecks = { path = "../../", package = "openchecks" }
pyo3-async-runtimes = { version = "0.23.0", features = [
    "attributes",
    "tokio-runtime",
] }
async-trait = "0.1.83"
