[package]
name = "pychecks"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pychecks"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20.3" }
checks = { path = "../../" }
pyo3-asyncio = { version = "0.20.0", features = [
    "attributes",
    "tokio-runtime",
] }
async-trait = "0.1.77"
