[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"

[tool.poetry]
name = "pychecks"
version = "0.1.0"
description = "A simple checks framework"
authors = ["Scott Wilson <scott@propersquid.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.group.dev.dependencies]
maturin = "^0.13.7"
pytest = "^7.2.0"
pytest-xdist = "^3.0.2"
pytest-cov = "^4.0.0"
hypothesis = "^6.57.1"
sphinx = "^5.3.0"
sphinx-rtd-theme = "^1.1.1"
myst-parser = "^0.18.1"
