[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pychecks"
version = "0.1.0"
description = "A simple checks framework"
authors = ["Scott Wilson <scott@propersquid.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
pytest-xdist = "^3.0.2"
pytest-cov = "^4.0.0"
hypothesis = "^6.67.1"
sphinx = "^5.3.0"
sphinx-rtd-theme = "^1.1.1"
myst-parser = "^0.18.1"
pytest-asyncio = "^0.20.3"
