name: C Test Suite
on: [push, pull_request]

jobs:
  test:
    name: C test
    defaults:
      run:
        working-directory: bindings/c
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy
      - name: Run Test
        run: |
          mkdir -p build
          cmake -S . -B build
          cmake --build build --config=Debug
          cd build
          ctest
