name: C Test Suite

on:
  push:
    paths:
      - "bindings/c/**"
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "bindings/c/**"
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/**"

jobs:
  test:
    name: C test
    defaults:
      run:
        working-directory: bindings/c
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy
      - name: Make Build Directory
        run: mkdir -p build
      - name: CMake Configure
        working-directory: bindings/c/build
        run: |
          # Make cmocka a static dependency when testing.
          cmake ../ -DBUILD_SHARED_LIBS=OFF
      - name: CMake Build
        working-directory: bindings/c/build
        run: |
          cmake --build . --config=Debug
      - name: Run Test
        working-directory: bindings/c/build
        run: ctest -C Debug -VV --output-on-failure
      - name: Run Valgrind
        working-directory: bindings/c/build
        run: |
          valgrind tests/test_check
          valgrind tests/test_item
          valgrind tests/test_result
          valgrind tests/test_runner
          valgrind tests/test_status
