on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type'
        type: choice
        required: true
        options:
        - major
        - minor
        - patch
        - premajor
        - preminor
        - prepatch
        - prerelease
        default: patch
      prerelease-identifier:
        description: 'Pre-release identifier (only for pre-release builds)'
        required: false

name: '[autorelease] Prepare release PR'

permissions:
  contents: read

jobs:
  changelog:
    name: Update changelog and create PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        ref: ${{ github.head_ref }}

    - name: Update changelog
      id: update-changelog
      uses: release-flow/keep-a-changelog-action@74931dec7ecdbfc8e38ac9ae7e8dd84c08db2f32 # v3.0.0
      with:
        command: bump
        version: ${{ github.event.inputs.release-type }}
        preid: ${{ github.event.inputs.prerelease-identifier }}

    - name: 'Setup Python'
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: '3'
    - name: 'Prepare Package Release'
      run: 'python scripts/prepare.py ${{ steps.update-changelog.outputs.version }}'

    - name: 'Ensure autorelease label exists'
      run: |
        LABEL=$(gh api repos/$GITHUB_REPOSITORY/labels --jq '.[] | select(.name=="autorelease")')
        if [[ -z "$LABEL" ]]; then
          echo "Creating 'autorelease' label"
          gh api --silent repos/$GITHUB_REPOSITORY/labels -f name="autorelease" -f color="baa938" -f description="This is an automatically-created PR to trigger a release"
        else
          echo "'autorelease' label exists"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Pull Request
      id: create-release-pr
      uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
      with:
        commit-message: 'chore: Update project files release ${{ steps.update-changelog.outputs.version }}'
        committer: 'releasebot <noreply@github.com>'
        branch: 'autorelease/${{ steps.update-changelog.outputs.version }}'
        title: '[autorelease] Release ${{ steps.update-changelog.outputs.version }}'
        # Be careful of newlines here. We need to use the literal block chomping style (|) so that the
        # contents of the release notes don't get chomped. See https://yaml-multiline.info/
        body: |
          **This PR was created automatically by the releasebot**

          :warning: **Approving this PR will trigger a workflow that generates a draft release. You need to publish this release when you are happy with it.**

          The changes in this PR prepare for release ${{ steps.update-changelog.outputs.version }}. The generated release notes will be:

          ---

          ${{ steps.update-changelog.outputs.release-notes }}
        labels: autorelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Output summary
      run: |
        echo "::notice:: Created a release PR, please merge it to continue with the release process: ${{
        steps.create-release-pr.outputs.pull-request-url }}"
